alias 4go='gogogogo'
alias be='bundle exec'
alias clr='clear'
alias cls='clear'
alias cmdstatistics='history | awk '\''{print $2}'\'' | awk '\''BEGIN{FS="|"}{print $1}'\'' | sort | uniq -c | sort -n | tail -n 20 | sort -nr'
alias cuke='bundle exec cucumber'
alias fuke='bundle exec cucumber --format Cucumber::Formatter::Fuubar'
alias gem='ruby -e "raise \"SUDO GEM DETECTED. Unalias gem at your own risk\" if ENV[\"USER\"] == \"root\"" && gem'
alias gitcuke='cuke `echo $(git st | grep "\.feature" | grep -v deleted | cut -f 2 -d "#" | cut -f 2 -d ":" | uniq)`'
alias gitprune='git remote prune origin'
alias gitspec='bundle exec rspec `echo $(git st | grep _spec.rb | grep -v deleted | cut -f 2 -d "#" | cut -f 2 -d ":" | uniq)`'
alias gogogo='passenger stop && git submodule update --init && bundle && killspork && be rake db:migrate db:seed db:test:prepare && bundle exec compass clean && pass'
alias gogogogo='passenger stop && git submodule update --init && bundle && killspork && be rake db:fix && bundle exec compass clean && pass'
alias gst='git status'
alias guard='bundle exec guard'
alias gut='git'
alias h='history | grep'
alias httpheaders='curl -I'
alias jasmine='be rake jasmine'
alias killruby='passenger stop && ps aux | grep ruby | grep -v grep | awk '\''{print $2}'\'' | xargs kill -9 && passenger start -d'
alias killspork='ps aux | grep spork | grep -v grep | awk '\''{print $2}'\'' | xargs kill -9'
alias l='ls -l'
alias less='less -R'
alias ll='ls -l'
alias mivm='mvim'
alias mvim='echo  > .vimlog && mvim -V3.vimlog'
alias myip='ifconfig | grep inet  | grep -v 127.0.0.1 | cut -d\   -f2'
alias mysql='/usr/local/mysql/bin/mysql'
alias mysqladmin='/usr/local/mysql/bin/mysqladmin'
alias netstat='lsof -i -P'
alias octopress='ssh -i jeff-ruby.pem bitnami@ec2-107-22-24-73.compute-1.amazonaws.com'
alias pass='(passenger stop && passenger start -d) || echo '\''failed to restart passenger!'\'''
alias pg='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log'
alias prd='pwd -P'
alias rake='be rake'
alias rebasemaster='git fetch && git rebase origin/master || sadface'
alias reload='source ~/.bash_profile'
alias rspec='bundle exec rspec'
alias rspork='bundle exec rspec --drb'
alias rvm-restart='rvm_reload_flag=1 source '\''/Users/jeffsaracco/.rvm/scripts/rvm'\'''
alias sadface='(echo; echo "/-------\\"; echo "| *   * |"; echo "|  ___ ,|";  echo "| /   \\ |";  echo "\\-------/"; echo; false)'
alias shouty='sudo osascript -e "set Volume 10"'
alias shutupvim='rm /var/tmp/*.sw*'
alias spec='bundle exec spec'
alias specchanges='be spec $(git status --porcelain | grep _spec.rb | awk \{print\ \$2\})'
alias speedtest='wget --delete-after http://cachefly.cachefly.net/10mb.test'
alias spork='title Spork; spork; title Shell'
alias sporky='killspork; thor spork:start; thor cucumber_spork:start'
alias sudo='sudo '
alias sysrake='env rake'
alias tmigrate='be rake db:migrate && be rake db:migrate:redo && be rake db:structure:dump && be rake db:test:prepare'
alias vi='vi -u /usr/share/vim/vimrc'
alias vim='mvim'
alias whopaired='git log --format=format:"%ad %an" --date=short | sort | uniq -c'
alias irb_record='script -a `date '+%m-%d-%Y'`.irb irb'

